name: Deploy pipeline
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # Add your Docker Hub credentials to your GitHub repository secrets
  # as DOCKER_USERNAME and DOCKER_PASSWORD
  test-server:
    name: testing-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - run: >-
          docker build -t dockeruser/fullstack-mern-server -f
          server/Dockerfile.dev ./server
      - run: docker run -e CI=true dockeruser/fullstack-mern-server npm test
  test-client:
    name: testing-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - run: >-
          docker build -t dockeruser/fullstack-mern-client -f
          client/Dockerfile.dev ./client
      - run: docker run -e CI=true dockeruser/fullstack-mern-client npm test
      - run: docker build -t dockeruser/mern-client ./client
      - run: docker build -t dockeruser/mern-nginx ./nginx
      - run: docker build -t dockeruser/mern-server ./server
      - run: docker push dockeruser/mern-client
      - run: docker push dockeruser/mern-nginx
      - run: docker push dockeruser/mern-server
      # The following steps are for deploying to AWS Elastic Beanstalk
      # Change the values below to match your AWS account
      # - application_name: <your application name>
      # - environment_name: <your application environment name>
      # - existing_bucket_name: <the Elastic Beanstalk S3 Bucket created for the region the app was created in>
      # - region: <The region of the app and S3 Bucket>
  deploy-to-aws:
    name: deploy-aws
    runs-on: ubuntu-latest
    needs: [test-client, test-server]
    steps:
      - uses: actions/checkout@v4
      - run: zip -r deploy.zip . -x '*.git*'
      - uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: "${{ secrets.AWS_ACCESS_KEY }}"
          aws_secret_key: "${{ secrets.AWS_SECRET_KEY }}"
          application_name: mern-beanstalk
          environment_name: Mern-beanstalk-env
          existing_bucket_name: elasticbeanstalk-eu-west-2-318746526342
          region: eu-west-2
          version_label: "${{ github.sha }}"
          deployment_package: deploy.zip
